# Generated by Django 3.2.4 on 2021-06-21 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productname', models.CharField(max_length=100)),
                ('productquantity', models.CharField(max_length=100)),
                ('productstock', models.IntegerField(max_length=100)),
                ('productprice', models.FloatField(max_length=100)),
                ('productimage', models.ImageField(upload_to='')),
            ],
        ),
    ]
