# Generated by Django 3.2.4 on 2021-06-24 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productquantity',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='productstock',
            field=models.CharField(max_length=100),
        ),
    ]
